### ISSUE TITLE
ロードバランサアプライアンスのubuntuでの導入設定について

### ISSUE THREAD

**Issue by tomokitamaki** [sakura-internet/cloud-manual#14]
URL: [ロードバランサ](https://manual.sakura.ad.jp/cloud/network/load-balancer.html)

[導入設定](https://manual.sakura.ad.jp/cloud/network/load-balancer.html#id13)のubuntuの部分でも

- /etc/sysctl.conf にカーネルパラメータの設定が必要なこと
- ループバックアドレス ロードバランサのVIPの設定が必要なこと

の2点が分かるような構成にしていただきたいです。  
今の構成だと項番が振られてないこともあり、CentOS7系CentOS8系でしか必要ないように見えやすそうです。  
(実際、ぼくが読み飛ばしてしまい設定がうまく出来ませんでした。)

/etc/sysctl.conf に  

```plane
net.ipv4.conf.all.arp_ignore = 1
net.ipv4.conf.all.arp_announce = 2
```

を追加して、 `sudo sysctl -p` で反映させるのと、 　
/etc/netplan/01-netcfg.yaml  (等)に  

```yaml
    lo:
      match:
        name: lo
      addresses:
        - 192.168.1.201/32 #ロードバランサのVIP
```

って感じで書いて、 `sudo netplan apply` で反映させる旨を追記いただければ幸いです。  

ご検討のほど、よろしくお願いします。

---

ぼくの環境
```shell
ubuntu@swarm-manager001:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
ubuntu@swarm-manager001:~$ 
```
